### ISSUE TITLE
Artifacts on the tiger demo

### ISSUE THREAD

**Issue by nical** [pcwalton/pathfinder#134] opened 2019-04-16 14:30 UTC
Screen cast: https://bugzilla.mozilla.org/attachment.cgi?id=9058611

Particularly visible towards of the video, small white shapes flicker as the tiger is panned. It's very easy to reproduce.

It *looks* like missing opaque tiles letting the white background bleed through occasionally, but it's hard to tell at a glance.

**Comment by nical** [comment] 2019-04-16 15:13
I can reproduce this on both intel and nvidia GPUs.

![Screenshot from 2019-04-16 16-59-22](https://user-images.githubusercontent.com/264854/56221505-a99dc600-606a-11e9-9ff2-5501eb235141.png)

A quick look in renderdoc shows that the white shape does not belong to the background, it is rendered on top of already-rendered black pixels of the eyes in the image above, as part of one of the non-opaque passes.

**Comment by nical** [comment] 2019-04-17 17:57
This reduced test case might be easier to investigate: https://bugzilla.mozilla.org/attachment.cgi?id=9059047

**Comment by pcwalton** [comment] 2019-04-18 20:59
Yeah, I'm aware of this. Thanks for the test case :)

**Comment by pcwalton** [comment] 2019-05-09 00:54
I'm having trouble reproducing, but this might be fixed by https://github.com/pcwalton/pathfinder/commit/3310b158262542b73b5989fc5d2306b3f16f8254.

@nical Could you check when you get a chance?

**Comment by nical** [comment] 2019-05-09 07:34
I can still reproduce *a* glitch, I'm not 100% certain it is the same bug but it is also reproducible for me with the reduced test case at the default zoom level, or on the tiger at any zoom level.

Here is a screen cast showing the (new?) glitch on the tiger: https://bugzilla.mozilla.org/attachment.cgi?id=9063716

I'm not sure this is the same issue because:
- simply moving the mouse without changing drawing parameters causes this issue to "flicker" whereas it was stable before, 
- the incorrect shape when I originally filed this used to somewhat match the correct contour, now it looks like a tile is randomly picking the wrong mask (index overflow?).

**Comment by pcwalton** [comment] 2019-05-09 19:15
OK, I definitely can't reproduce that. Are you on Linux?

**Comment by nical** [comment] 2019-05-10 13:01
Yes, reproducing this both on intel and nvidia GPUs (using the proprietary drivers for nvidia).

**Comment by tmpvar** [comment] 2019-05-11 18:11
I'm seeing similar behavior on windows w/ nvidia @ a5d373cb91a6f49a7f0019e1f4a4b9180d840bda

![pathfinder](https://user-images.githubusercontent.com/46673/57573503-67ec0b00-73dd-11e9-92b7-7e7b3454bf1a.gif)

**Closed** 2019-05-13 17:58 UTC
Labels: bug
