### ISSUE TITLE
Can't run example.GLSL 4.1 is not supported - Debian Stretch 

### ISSUE THREAD

**Issue by tupshin** [pcwalton/pathfinder#4] opened 2017-02-14 22:29 UTC
```cargo run --release --example lorem-ipsum -- resources/tests/nimbus-sans/NimbusSanL-Regu.ttf```

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompileFailed("Tessellation control shader", "0:11(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, 3.00 ES, and 3.10 ES\n\u{0}")', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837```

I assume this is not unexpected with that GLSL version, but figured you might as well have an issue for it.

Debian Stretch (Testing)

**Comment by pcwalton** [comment] 2017-02-14 23:59
Which GPU are you using?

**Comment by juninho** [comment] 2017-02-15 01:27
Same here. I tested with Haswell integrated (in Debian SID).
Mesa 13 (current version in stretch and sid) doesn't have OpenGL 4.5 support for intel haswell yet.

Fortunately, Mesa 17 added this support: http://phoronix.com/scan.php?page=news_item&px=Mesa-17.0-Released

It's already in Debian experimental and probably in next couple of weeks will be available in unstable also.

**Comment by tupshin** [comment] 2017-02-15 12:36
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b) (prog-if 00 [VGA controller])
	Subsystem: Dell Haswell-ULT Integrated Graphics Controller
	Flags: bus master, fast devsel, latency 0, IRQ 48
	Memory at f7800000 (64-bit, non-prefetchable) [size=4M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915

Dell Latitiude E7440

**Comment by torokati44** [comment] 2017-02-15 21:54
FYI compiles/runs/works fine on Ivy Bridge (i7-3632QM, HD4000, a predecessor of Haswell) and Fedora 25 with some patches from the Igalia repo applied on top of Mesa 17.0.0. (Although the "benchmark" example doesn't seem to update the front buffer, I don't know if that's expected.)
The link to the repository I got the patches from can be found in this mail: https://lists.freedesktop.org/archives/mesa-dev/2017-February/144325.html
Although I have not only cherry-picked the -rc3 branch, but a few WIP commits on top of that, giving me OpenGL 4.20.
AFAIK the commits enabling 4.0 are well on their way into the mainstream tree, the ones for 4.20 not so much yet. So we (Gen7 users) have to get compiling, or be patient for now.

**Comment by awalgarg** [comment] 2017-02-27 14:58
I had the same issue. After installing Mesa 17 (which landed in the Arch Linux official repos recently, no special patches on my end), the issue disappeared and the examples work great.

**Comment by pcwalton** [comment] 2017-02-27 19:10
I've been behind on compat lately. I'm planning to take a pass later this week and fix the compatibility regressions that have happened.

**Comment by geomaster** [comment] 2017-03-07 21:31
Same here, but the problem is likely that my GPU simply doesn't support tessellation. Out of curiosity, what is tessellation being used for in Pathfinder?

**Comment by codeyash** [comment] 2017-05-15 18:20
Linux mint 18 with latest update facing same problem described in this thread. Please fix this. :)

**Comment by codeyash** [comment] 2017-05-22 21:09
It's all new to me. I able to find something I'm not sure how much helpful but

https://github.com/pcwalton/pathfinder/blob/master/resources/shaders/draw.tes.glsl
and
https://github.com/pcwalton/pathfinder/blob/master/resources/shaders/draw.tcs.glsl

We're using #version 410 and in rest #330.

I debug program and it's crashing during loading these files.

One more observation.

PATHFINDER_FORCE_GEOMETRY_SHADER=1 RUST_BACKTRACE=1 cargo run

With this it shows windows and glyph blocks (no text) if it suppose to show this. I'm again not sure what should it display. Here is screenshot.

![image](https://cloud.githubusercontent.com/assets/654242/26328479/d722fbb8-3f60-11e7-8d54-55f9f2cc60e0.png)

If we fix two glsl files we may able to run on my last comment profile I think.

**Comment by pcwalton** [comment] 2017-08-27 08:10
I've tagged this issue as "classic", as it likely only applies to Pathfinder 1 ("classic Pathfinder"). Once Pathfinder 2 matures, this issue will be closed. Feel free to reopen if it is still an issue with the new version. Thanks!

**Comment by pcwalton** [comment] 2017-10-07 07:00
This issue affected Pathfinder 1, which is now obsolete. Please feel free to reopen if this is still an issue with Pathfinder 2.

**Closed by pcwalton** 2017-10-07 07:00 UTC
Labels: classic, compatibility
