### ISSUE TITLE
White screen on 2014 Retina MBP

### ISSUE THREAD

**Issue by mmastrac** [pcwalton/pathfinder#3] opened 2017-02-14 21:30 UTC
Running gfxCardStatus, app appears to switch to using the discrete GPU when launching sample app. Switches back to integrated when sample app is terminated.

Doesn't appear to be related to the switch from integrated to discrete as I launched two copies of the app and neither works.

System profiler:

```Intel Iris Pro:

  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x0d26
  Revision ID:	0x0008
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal:	Supported

NVIDIA GeForce GT 750M:

  Chipset Model:	NVIDIA GeForce GT 750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2048 MB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x0fe9
  Revision ID:	0x00a2
  ROM Revision:	3776
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal:	Supported
  Displays:
Color LCD:
  Display Type:	Retina LCD
  Resolution:	2880 x 1800 Retina
  Retina:	Yes
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Built-In:	Yes

```

**Comment by TimNN** [comment] 2017-02-14 21:39
This could be a duplicate of / related to #2.

**Comment by pcwalton** [comment] 2017-02-14 22:14
Assuming this is a driver bug.

**Comment by pcwalton** [comment] 2017-08-27 08:09
I've tagged this issue as "classic", as it likely only applies to Pathfinder 1 ("classic Pathfinder"). Once Pathfinder 2 matures, this issue will be closed. Feel free to reopen if it is still an issue with the new version. Thanks!

**Comment by pcwalton** [comment] 2017-10-07 07:00
This issue affected Pathfinder 1, which is now obsolete. Please feel free to reopen if this is still an issue with Pathfinder 2.

**Closed by pcwalton** 2017-10-07 07:00 UTC
Labels: classic, compatibility, driver bug
